-- Enable pgvector
CREATE EXTENSION IF NOT EXISTS vector;

-- Stores the current content hash for each knowledge source
CREATE TABLE knowledge_documents (
    source VARCHAR(512) PRIMARY KEY,
    content_hash VARCHAR(64) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Stores individual knowledge chunks and their embeddings
CREATE TABLE knowledge_chunks (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source VARCHAR(512) NOT NULL,
    chunk_index INTEGER NOT NULL,
    content TEXT NOT NULL,
    metadata JSONB NOT NULL,
    source_hash VARCHAR(64) NOT NULL,
    embedding VECTOR(384) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_knowledge_source_chunk
        UNIQUE (source, chunk_index)
);

-- Used when filtering/searching chunks by source
CREATE INDEX ix_knowledge_chunks_source
    ON knowledge_chunks (source);

-- Vector similarity search using cosine distance
CREATE INDEX knowledge_chunks_embedding_hnsw
    ON knowledge_chunks
    USING hnsw (embedding vector_cosine_ops);